pwordcount: pwordcount.c helper.c
	@echo "Starting to compile pwordcount..."
	gcc -o pwordcount pwordcount.c helper.c
	@echo "Finished!"

clean:
	@echo "Removing pwordcount executable..."
	rm -f pwordcount
	@echo "Finished!"
